#
## DataSource Config
#spring:
#  datasource:
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.56.10:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#  application:
#    name: gulimall-coupon
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#      # 配置中心
##      config:
##        group: DEFAULT_GROUP
##        server-addr: 127.0.0.1:8848
##        file-extension: properties
##        enabled: true
##        refresh-enabled: true
##  config:
##    import:
##      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
#
#mybatis-plus:
#  #  classpath* 加载自身+引用的其它文件
#  #  classpath 加载自身
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      #      实体类上@TableId实现自增
#      id-type: auto
#
#server:
#  port: 8100
